### ISSUE TITLE
collate="rows" strips Date objects into numeric

### ISSUE THREAD

**Issue by sdanielzafar** [hadley/purrrlyr#5] opened 2018-02-07 20:19 UTC
```
library(tidyverse)
library(purrrlyr)

data("storms")

storms %>% 
    head(100) %>% 
    mutate(Date = as.Date(paste0(year, "-", month, "-", day))) %>% 
    by_row(function(.d) {select(.d, Date)}, .to = "new", .collate = "rows")
```
which yeilds:
```
# tibble [100 × 16]
   name   year month   day  hour   lat  long status              category  wind pressure ts_diameter hu_diameter Date        .row  Date
   <chr> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <chr>               <ord>    <int>    <int>       <dbl>       <dbl> <date>     <int> <dbl>
 1 Amy    1975  6.00    27  0     27.5 -79.0 tropical depression -1          25     1013          NA          NA 1975-06-27     1  2003
 2 Amy    1975  6.00    27  6.00  28.5 -79.0 tropical depression -1          25     1013          NA          NA 1975-06-27     2  2003
 3 Amy    1975  6.00    27 12.0   29.5 -79.0 tropical depression -1          25     1013          NA          NA 1975-06-27     3  2003
 4 Amy    1975  6.00    27 18.0   30.5 -79.0 tropical depression -1          25     1013          NA          NA 1975-06-27     4  2003
 5 Amy    1975  6.00    28  0     31.5 -78.8 tropical depression -1          25     1012          NA          NA 1975-06-28     5  2004
 6 Amy    1975  6.00    28  6.00  32.4 -78.7 tropical depression -1          25     1012          NA          NA 1975-06-28     6  2004
 7 Amy    1975  6.00    28 12.0   33.3 -78.0 tropical depression -1          25     1011          NA          NA 1975-06-28     7  2004
 8 Amy    1975  6.00    28 18.0   34.0 -77.0 tropical depression -1          30     1006          NA          NA 1975-06-28     8  2004
 9 Amy    1975  6.00    29  0     34.4 -75.8 tropical storm      0           35     1004          NA          NA 1975-06-29     9  2005
10 Amy    1975  6.00    29  6.00  34.0 -74.8 tropical storm      0           40     1002          NA          NA 1975-06-29    10  2005
# ... with 90 more rows
```
but Date column should be of `Date` class.

**Comment by lionel-** [comment] 2018-11-15 08:11
Duplicate of #3. To solve this in the general case, this would require new infrastructure that is being developed in the vctrs package. But note that while purrrlyr is still maintained, it is no longer under active development.

**Closed as completed by lionel-** 2018-11-15 08:11 UTC

**Comment by lorenzwalthert** [comment] 2018-11-15 09:10
In this case, should a life-cycle badge be added to this repo?

**Comment by lionel-** [comment] 2018-11-15 09:16
There is a lifecycle badge in the README.

**Comment by lorenzwalthert** [comment] 2018-11-15 09:21
Sorry, was not passionate enough to wait for the full page to be loaded -.-  Thanks.
